package railo.runtime.flash;

import java.io.InputStream;

public interface FlashEngine {

	/**
	 * return flash generated by the flashEngine
	 * @param input xml input
	 * @return genereted flash
	 */
	public InputStream createFlash(String input);
}
