
		<cfapplication name="webadmin" 
		sessionmanagement="yes" 
		clientmanagement="no" 
		setclientcookies="yes" 
		setdomaincookies="no"><cfsetting showdebugoutput="no"><cfcontent type="image/gif" variable="#evaluateJava('rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAIKiVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAACXBIWXMAAAsTAAALEwEAmpwYAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABuJwAAc68AAPd6AACFVQAAcPsAAOOkAAAyqwAAHJY/IjnCAAABgElEQVR42pTSzSvDARwG8AcbzRA28pKXtsMi89KQ0ArZJHmJjBZx2U3KJC8HxZaDXJzIvOTgMsNtXi7swE1JotDIeygvxeTl8Rf8fua5f3r69n2C4Gfa6sttk1aTK1VbVLx7dLLhFyoy1tkPNxfIDhVf+ltZUGYckPyFDIYK++j4VP/u5Tk27jTQBf/g7uriSxQZK2psj68e3ngnaDKZ2dzZS61O5wQQI4j0esOQ92GH/LSSjkjOdJupyihYBhAhiPLyS0bO7rdJXxc/JxPp7qilRqNxiaLsnMLh42sP+W6lz6HmkqWKypS0RQAKQaTNzLXte9fJ7x5+ONRcaDcwOl69CCBSEKVn6ex7p26SfeR0MufNpZQrk5YBhAsiiTSiesU1RnKQnFNxulHPkKh4l2gTEBhsqizZe3D38na2jI6mXIaExThFbwIgkcrCGuIUssy1zQNMrV7Tc3zj/Hl7sgB4Fn1yqFxuiY1L8AVIZVsAWgDI/N2vEoAeQCL+kd8BAJdvnSeNEzLrAAAAAElFTkSuQmCC')#">
	