
		<cfapplication name="webadmin" 
		sessionmanagement="yes" 
		clientmanagement="no" 
		setclientcookies="yes" 
		setdomaincookies="no"><cfsetting showdebugoutput="no"><cfcontent type="image/gif" content="#evaluateJava('rO0ABXVyAAJbQqzzF/gGCFTgAgAAeHAAAAEeR0lGODlhIAAEANUAAHBdVm5bVGRTTXNgWmtaU21bVXFeV29cVWZVUFpMRmBRS29dVlhKRWJRTF1OSFVHQmRTTmtZUm1aVHNfWGNSTXFfWGdWT3NfWWhWUWxZU1ZIQ3NgWXRhWnRgWXJfWHZiW3VhW3VhWnViWwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAgAAQAAAY7wIeGkXAoBJZIAODphJ7QqDTaoEAQGEJhUdlwRODwZ0wuf6IZSeAAMHgG4bh8PvdMLh3nB8Tv+/+AUUEAOw==')#">
	