package railo.runtime.db.driver;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import railo.runtime.PageContext;

public interface StatementPro extends Statement {

	public boolean execute(PageContext pc,String sql) throws SQLException;

	public boolean execute(PageContext pc,String sql, int autoGeneratedKeys) throws SQLException;

	public boolean execute(PageContext pc,String sql, int[] columnIndexes) throws SQLException;

	public boolean execute(PageContext pc,String sql, String[] columnNames) throws SQLException;

	public ResultSet executeQuery(PageContext pc,String sql) throws SQLException;

	public int executeUpdate(PageContext pc,String sql) throws SQLException;
	
	public int executeUpdate(PageContext pc,String sql, int autoGeneratedKeys) throws SQLException;

	public int executeUpdate(PageContext pc,String sql, int[] columnIndexes) throws SQLException;

	public int executeUpdate(PageContext pc,String sql, String[] columnNames) throws SQLException;

}
